// Code generated by jo. DO NOT EDIT. 
package handlers

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
)

func CreateUser_hdl(w http.ResponseWriter, r *http.Request) {
	req := &createUserRequest{}
	resp := &createUserResponse{}

	reqData, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Fatal(err)
	}

	if err = json.Unmarshal(reqData, req); err != nil {
		log.Fatal(err)
	}

	resp, err = CreateUser(r.Context(), req)
	if err != nil {
		log.Println(err)
	}

	b, err := json.Marshal(resp)

	if err != nil {
		log.Fatal(err)
	}

	_, _ = w.Write(b)
}

func GetUser_hdl(w http.ResponseWriter, r *http.Request) {
	req := &IDRequest{}
	resp := &UserResponse{}

	reqData, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Fatal(err)
	}

	if err = json.Unmarshal(reqData, req); err != nil {
		log.Fatal(err)
	}

	resp, err = GetUser(r.Context(), req)
	if err != nil {
		log.Println(err)
	}

	b, err := json.Marshal(resp)

	if err != nil {
		log.Fatal(err)
	}

	_, _ = w.Write(b)
}
